DROP TABLE websites CASCADE CONSTRAINTS;
DROP TABLE smartphones CASCADE CONSTRAINTS;
DROP TABLE users CASCADE CONSTRAINTS;
DROP TABLE reviews CASCADE CONSTRAINTS;

CREATE TABLE websites (
                          website_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
                          web_address VARCHAR2(100) NOT NULL,
                          name VARCHAR2(40) NOT NULL,
                          yearly_users NUMBER,
                          mobile_app CHAR(1), --Boolean
                          server_country VARCHAR2(25),
                          CONSTRAINT WEBSITE_ID PRIMARY KEY (website_ID),
                          CONSTRAINT WEB_ADDRESS CHECK (REGEXP_LIKE(web_address, '^www\.[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'))
);


CREATE TABLE smartphones (
                             phone_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
                             name VARCHAR2(30) NOT NULL,
                             release_date DATE,
                             screen_diagonal NUMBER(3,2),
                             camera_amount NUMBER,
                             processor_cores NUMBER,
                             memory NUMBER,
                             storage NUMBER,
                             CONSTRAINT SMARTPHONE_ID PRIMARY KEY (phone_ID)
);


CREATE TABLE users (
                       user_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
                       first_name VARCHAR2(20) NOT NULL,
                       last_name VARCHAR2(40) NOT NULL,
                       email VARCHAR2(100) NOT NULL,
                       phone_number VARCHAR2(15),
                       birthdate DATE,
                       CONSTRAINT USER_ID PRIMARY KEY (user_ID)
);


CREATE TABLE reviews (
                         review_user_ID NUMBER NOT NULL,
                         review_phone_ID NUMBER NOT NULL,
                         postedDate DATE NOT NULL,
                         website_ID NUMBER NOT NULL,
                         title VARCHAR2(125) NOT NULL,
                         content VARCHAR2(250) NOT NULL,
                         likes NUMBER,
                         rating NUMBER NOT NULL,
                         last_edited_date DATE,
                         CONSTRAINT REVIEW_ID PRIMARY KEY (review_user_ID, review_phone_ID, postedDate),
                         CONSTRAINT RATING CHECK (rating between 0 AND 5)
);


ALTER TABLE reviews ADD CONSTRAINT WEBSITES_REVIEWS_FK
    FOREIGN KEY (website_ID)
        REFERENCES websites (website_ID)
            NOT DEFERRABLE;

ALTER TABLE reviews ADD CONSTRAINT SMARTPHONES_REVIEWS_FK
    FOREIGN KEY (review_phone_ID)
        REFERENCES smartphones (phone_ID)
            NOT DEFERRABLE;

ALTER TABLE reviews ADD CONSTRAINT USERS_REVIEWS_FK
    FOREIGN KEY (review_user_ID)
        REFERENCES users (user_ID)
            NOT DEFERRABLE;